version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: FitBuddy
      MYSQL_USER: Stoyan
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8081:8080

  app:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: Stoyan
      DB_PASSWORD: pass123
      DB_NAME: FitBuddy
    depends_on:
      - db
    ports:
      - "8080:8080"
